builds:
-
  binary: "tkm"
  env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
-
  # Repository to push the tap to.
  github:
    owner: SimantovYousoufov
    name: homebrew-tap

  # Git author used to commit to the repository.
  # Defaults are shown.
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com

  # Folder inside the repository to put the formula.
  # Default is the root folder.
  folder: Formula

  # Your app's homepage.
  # Default is empty.
  homepage: "https://github.com/SimantovYousoufov/taskmaster"

  # Your app's description.
  # Default is empty.
  description: "Taskmaster is a better way to manage your tasks."

  # So you can `brew test` your formula.
  # Default is empty.
  test: |
    system "#{bin}/tkm --version"
